algo  = input("Digite algo: ")
print("O tipo primitivo do {} é:".format(algo),type(algo))
print("Só tem espaço: ", algo.isspace())
print("o {} é númerico? :".format(algo),algo.isnumeric())
print("o {} é alfabetico? :".format(algo),algo.isalpha())
print("o {} é alphanumerico: ".format(algo),algo.isalnum())
print("o {} é maiusculo :".format(algo), algo.isupper())
print("o {} é minusculas:  ".format(algo), algo.islower())
print("o {} Está capitalizada:".format(algo), algo.istitle())
